### ISSUE TITLE
Themer- Unrecoverable crash

### ISSUE THREAD

**Issue by ItsLogic** [Vendicated/AliucordPlugins#16]
# Error
Made a theme with a font url
Causes aliucord to crash when applied
Themer still applies the font and rest of the theme when the app starts back up

# Theme
```
{
  "mention_highlight": 452930707,
  "simple_bg_color": -15461356,
  "simple_bg_secondary_color": -15658735,
  "simple_accent_color": -36169,
  "font": "https://github.com/ItsLogic/Theme-Stuff/blob/main/Lexend-Regular.ttf?raw=true"
}
```
# Crashlogs
```
java.lang.IllegalStateException: Must be called from main thread
	at android.app.Activity.recreate(Activity.java:6358)
	at com.aliucord.plugins.themer.ThemeManager.loadFont(ThemeManager.java:152)
	at com.aliucord.plugins.themer.ThemeManager.lambda$loadFont$1(ThemeManager.java:163)
	at com.aliucord.plugins.themer.-$$Lambda$ThemeManager$rAMf-XEC1VcaQPvAghdMLv8oAbs.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
```

**Comment by Vendicated** [comment]
Fixed in https://github.com/Vendicated/AliucordPlugins/commit/027e184f2b4fba68e81555344de5693fe748ea7f
