### ISSUE TITLE
[BetterSpotify] Plugin seems to have stopped working.

### ISSUE THREAD

**Issue by WhenFreedom** [Vendicated/AliucordPlugins#54]
BetterSpotify used to work flawlessly a while ago. I only just reinstalled it after a while and sadly it has stopped working. 

Previously I'd have to play the exact same song the person is listening to, and then press "Listen Along" and the music would sync. 

Sadly this does not work anymore. 

I tested the plugin on a newer version of Spotify (with xManager). I thought it might have something to do with compatibility, then I downloaded the version of Spotify I used to use where I knew the listen along functionality worked for, however it still didn't work.

"Play on Spotify" button works flawlessly, but "Listen Along" does not. 

Regardless of listening to the same song the person is listening to, the plugin still says:
"Failed to play: Make sure your Spotify is running".

Error in Debug Log:

> [BetterSpotify] Failed to play. Make sure your Spotify is running
com.aliucord.Http$HttpException: 404: Not Found (https://api.spotify.com/v1/me/player/play)
  at com.aliucord.Http$Response.assertOk(Http.java, [BetterSpotify] Failed to play. Make sure your Spotify is running:448)
  at dev.vendicated.aliucordplugins.betterspotify.SpotifyApi.request$lambda-4(SpotifyApi.kt:78)
  at dev.vendicated.aliucordplugins.betterspotify.SpotifyApi.$r8$lambda$5AoAYxkWKQABjNyqB94Y5vk0pSY(Unknown Source:0)
  at dev.vendicated.aliucordplugins.betterspotify.SpotifyApi$$ExternalSyntheticLambda0.run(Unknown Source:10)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  at java.lang.Thread.run(Thread.java:923)

**Comment by Vendicated** [comment]
It works fine, it is just not very stable because the Spotify api sucks and isn't meant for things like this
