### ISSUE TITLE
[Playable Embeds] Plugin crashes

### ISSUE THREAD

**Issue by QuickNET-Tech** [Vendicated/AliucordPlugins#66]
# Issue Description
Embeds that are playable (only tested with YouTube) will not have their embed image load and will crash momentarily after the embed becomes visible. Uninstalling the plugin resolves the issue for me in the mean time.

# Additional Details
Android Version: 12.0
Discord Version: 120.11
Aliucord Version: AE8A1AC

# Crash Log From Aliucord
```
java.lang.RuntimeException: Canvas: trying to draw too large(113836608bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
	at c.f.g.e.g.draw(ForwardingDrawable.java:2)
	at c.f.g.e.p.draw(ScaleTypeDrawable.java:7)
	at c.f.g.e.f.draw(FadeDrawable.java:25)
	at c.f.g.e.m.draw(RoundedCornersDrawable.java:22)
	at c.f.g.f.b.draw(RootDrawable.java:14)
	at android.widget.ImageView.onDraw(ImageView.java:1418)
	at android.view.View.draw(View.java:22369)
	at android.view.View.updateDisplayListIfDirty(View.java:21245)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21205)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21205)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21205)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21205)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21205)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21205)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21205)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21205)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21205)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21205)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21205)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21205)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4108)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3835)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3106)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1959)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8187)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
	at android.view.Choreographer.doCallbacks(Choreographer.java:878)
	at android.view.Choreographer.doFrame(Choreographer.java:811)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:7710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

**Comment by Vendicated** [comment]
The Stacktrace does not include my plugin or WebView at all, so it is likely a weird incompatibility with another plugin or something on your device. 
Or it is caused by the WebView implementation on your device being bad. In any case, I can't really do much about it sadly so I advise you to just not use the Plugin
